main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
	path('', views.home, name='home'),
	path('account/', views.account, name='account'),
	path('settings/', views.settings, name='settings'),
	path('settings/delete/<int:user_id>/', views.delete_user, name='delete_user'),
	path('settings/update/<int:user_id>/', views.update_user, name='update_user'),
	path('student/', views.student_list, name='student_list'),
	path('student/<int:student_id>/', views.student_details, name='student_details'),
	path('instructor/', views.instructor_list, name='instructor_list'),
	path('instructor/<int:instructor_id>', views.instructor_details, name='instructor_details'),

	# path('', views.index, name='index'),
]

mon_projet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls')),
    path('planning/', include('planning.urls')),
]

planning/urls.py
from django.urls import path
from . import views

app_name = 'planning'
urlpatterns = [
    path('', views.appointment_list, name='appointment_list'),
	path('add/', views.add_appointment, name='add_appointment'),
	path('add/<int:user_id>/', views.add_appointment, name='add_appointment_with_id'),
	path('edit/<int:pk>/', views.edit_appointment, name='edit_appointment'),
	path('delete/<int:pk>/', views.delete_appointment, name='delete_appointment'),
]

planning/models.py
# planning/models.py
from django.db import models
from django.conf import settings

class Appointment(models.Model):
	student = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='student_appointments')
	instructor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='instructor_appointments')
	date = models.DateField()
	timeStart = models.TimeField(null=True)
	timeEnd = models.TimeField(null=True)
	location = models.CharField(max_length=255)

	def __str__(self):
		return f"{self.student.username} - {self.date} at {self.timeStart} with {self.instructor.username}"

planning/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Appointment
from authapp.models import CustomUser
from django.utils.dateparse import parse_date, parse_time
from django.contrib import messages
from django.http import HttpResponseForbidden
from datetime import datetime

@login_required
def appointment_list(request, user_id=None):
    user = request.user
    if user_id:
        user_to_filter = get_object_or_404(CustomUser, id=user_id)
    else:
        user_to_filter = user
    
    appointments = []

    if user.roles == 'student':
        appointments = Appointment.objects.filter(student=user_to_filter)
        return render(request, 'appointment_student_list.html', {'appointments': appointments})
    elif user.roles == 'instructor':
        appointments = Appointment.objects.filter(instructor=user_to_filter)
        return render(request, 'appointment_instructor_list.html', {'appointments': appointments})
    elif user.roles == 'secretary' or user.roles == 'admin':
        appointments = Appointment.objects.all()
        return render(request, 'appointment_secretary_list.html', {'appointments': appointments})
    return render(request, 'appointment_student_list.html', {'appointments': appointments})


@login_required
def add_appointment(request, user_id=None):
	if user_id:
		user = get_object_or_404(CustomUser, id=user_id)
	else:
		user = request.user

	if request.method == 'POST':
		if user.roles == 'instructor':
			student = get_object_or_404(CustomUser, id=request.POST.get('student'))
			instructor = user
		elif user.roles == 'student':
			instructor = get_object_or_404(CustomUser, id=request.POST.get('instructor'))
			student = user
		else:
			student = get_object_or_404(CustomUser, id=request.POST.get('student'))
			instructor = get_object_or_404(CustomUser, id=request.POST.get('instructor'))

		date = request.POST.get('date')
		timeStart = request.POST.get('timeStart')
		timeEnd = request.POST.get('timeEnd')
		location = request.POST.get('location')

		# Convertir les temps en datetime
		start_datetime = datetime.combine(datetime.now().date(), datetime.strptime(timeStart, '%H:%M').time())
		end_datetime = datetime.combine(datetime.now().date(), datetime.strptime(timeEnd, '%H:%M').time())

		appointment_duration = (end_datetime - start_datetime).total_seconds() / 3600

		total_hours_taken = student.hours_taken + appointment_duration

		if total_hours_taken > student.hours_paid:
			messages.error(request, "Impossible d'ajouter le rendez-vous. Les heures totales prises dépasseraient les heures payées.")
			return redirect('planning:add_appointment')

		appointment = Appointment(
			student=student,
			instructor=instructor,
			date=date,
			timeStart=start_datetime.time(),
			timeEnd=end_datetime.time(),
			location=location
		)
		appointment.save()

		student.hours_taken += appointment_duration
		student.save()

		return redirect('planning:appointment_list')
	else:
		user = request.user
		print(user.roles)
		if user.roles == 'instructor':
			students = CustomUser.objects.filter(roles='student')
			return render(request, 'add_appointment.html', {'students': students})
		elif user.roles == 'student':
			instructors = CustomUser.objects.filter(roles='instructor')
			return render(request, 'add_appointment.html', {'instructors': instructors})
		else:
			students = CustomUser.objects.filter(roles='student')
			instructors = CustomUser.objects.filter(roles='instructor')
			return render(request, 'add_appointment.html', {'instructors': instructors, 'students': students})


@login_required
def edit_appointment(request, pk):
	appointment = get_object_or_404(Appointment, id=pk)
	student = appointment.student
	start_datetime = datetime.combine(datetime.now().date(), appointment.timeStart)
	end_datetime = datetime.combine(datetime.now().date(), appointment.timeEnd)
	appointment_duration1 = (end_datetime - start_datetime).total_seconds() / 3600
	print(appointment.student.hours_paid)
	if request.method == 'POST':
		date = request.POST.get('date')
		timeStart = request.POST.get('timeStart')
		timeEnd = request.POST.get('timeEnd')
		location = request.POST.get('location')
		appointment.date = parse_date(date)
		appointment.timeStart = parse_time(timeStart)
		appointment.timeEnd = parse_time(timeEnd)
		appointment.location = location

		start_datetime = datetime.combine(datetime.now().date(), appointment.timeStart)
		end_datetime = datetime.combine(datetime.now().date(), appointment.timeEnd)
		appointment_duration2 = (end_datetime - start_datetime).total_seconds() / 3600

		if appointment_duration2 > appointment_duration1:
			student.hours_taken += appointment_duration2 - appointment_duration1
			total_hours_taken = student.hours_taken
			if total_hours_taken > student.hours_paid:
				messages.error(request, "Impossible d'ajouter le rendez-vous. Les heures totales prises dépasseraient les heures payées.")
				return render(request, 'edit_appointment.html', {'appointment': appointment, 'student': student})
		elif appointment_duration2 < appointment_duration1:
			student.hours_taken -= appointment_duration1 - appointment_duration2
			total_hours_taken = student.hours_taken
			if total_hours_taken > student.hours_paid:
				messages.error(request, "Impossible d'ajouter le rendez-vous. Les heures totales prises dépasseraient les heures payées.")
				return render(request, 'edit_appointment.html', {'appointment': appointment, 'student': student})
		
		student.save()
		appointment.save()
		return redirect('planning:appointment_list')
	else:
		return render(request, 'edit_appointment.html', {'appointment': appointment, 'student': student})

@login_required
def delete_appointment(request, pk):
	appointment = get_object_or_404(Appointment, id=pk)

	start_datetime = datetime.combine(datetime.now().date(), appointment.timeStart)
	end_datetime = datetime.combine(datetime.now().date(), appointment.timeEnd)

	appointment_duration = (end_datetime - start_datetime).total_seconds() / 3600
	appointment.student.hours_taken -= appointment_duration
	appointment.student.save()
	appointment.delete()
	return redirect('planning:appointment_list')

planning/templates/add_appointment.html
{% extends 'base_generic.html' %}

{% block title %}My Appointments{% endblock %}

{% block content %}
<div>
	<h2 class="text-3xl font-extrabold text-gray-900">
		Ajouter un rendez-vous
	</h2>
</div>
<div class="flex items-center justify-center bg-gray-50" style="height: 80vh;display: flex;align-items: center;justify-content: center;">
    <div class="max-w-md w-full space-y-8">
		{% if messages %}
        <div class="alert alert-danger">
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        </div>
        {% endif %}
        <form method="post" class="space-y-6">
            {% csrf_token %}
            <div class="flex flex-col gap-5">
				{% if request.user.roles == 'instructor' or request.user.roles == 'secretary' or request.user.roles == 'admin' %}
					<div>
						<label for="student" class="sr-only">Étudiant</label>
						<select id="student" name="student" required class="w-full px-3 py-2 placeholder-gray-500 text-gray-900 focus:outline-none sm:text-sm">
							{% for student in students %}
								<option value="{{ student.id }}">{{ student.username }}</option>
							{% endfor %}
						</select>
					</div>
				{% endif %}
				{% if request.user.roles == 'student' or request.user.roles == 'secretary' or request.user.roles == 'admin' %}
					<div>
						<label for="instructor" class="sr-only">Instructeur</label>
						<select id="instructor" name="instructor" required class="w-full px-3 py-2 placeholder-gray-500 text-gray-900 focus:outline-none sm:text-sm">
							{% for instructor in instructors %}
								<option value="{{ instructor.id }}">{{ instructor.username }}</option>
							{% endfor %}
						</select>
					</div>
				{% endif %}
                <div>
                    <label for="date" class="sr-only">Date</label>
                    <input id="date" name="date" type="date" required class="w-full px-3 py-2 placeholder-gray-500 text-gray-900 focus:outline-none sm:text-sm">
                </div>
                <div>
                    <label for="timeStart" class="sr-only">Heure de début</label>
                    <input id="timeStart" name="timeStart" type="time" step="3600" required class="w-full px-3 py-2 placeholder-gray-500 text-gray-900 focus:outline-none sm:text-sm">
                </div>
                <div>
                    <label for="timeEnd" class="sr-only">Heure de fin</label>
                    <input id="timeEnd" name="timeEnd" type="time" step="3600" required class="w-full px-3 py-2 placeholder-gray-500 text-gray-900 focus:outline-none sm:text-sm">
                </div>
                <div>
                    <label for="location" class="sr-only">Lieu</label>
                    <input id="location" name="location" type="text" required class="w-full px-3 py-2 placeholder-gray-500 text-gray-900 focus:outline-none sm:text-sm" placeholder="Lieu">
                </div>
            </div>
            <div>
                <button type="submit" class="w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white focus:outline-none" style="background-color: #1f2937">
                    Ajouter
                </button>
            </div>
        </form>
        <div class="text-center">
            <a href="{% url 'planning:appointment_list' %}" class="text-sm text-black-600 hover:text-gray-500">
                Retour à la liste des rendez-vous
            </a>
        </div>
    </div>
</div>
{% endblock %}

planning/templates/appointment_instructor_list.html
{% extends 'base_generic.html' %}

{% block title %}My Appointments{% endblock %}

{% block content %}
<div>
	<h2 class="text-3xl font-extrabold text-gray-900">
		My Appointments instructor
	</h2>
</div>
<div class="flex items-center justify-center bg-gray-50" style="height: 80vh;display: flex;align-items: center;justify-content: center;">
    <div class="max-w-4xl w-full space-y-8">
        <div>
            {% if appointments %}
                <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                        <tr>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Date
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                TimeStart
                            </th>
							<th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                TimeEnd
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Location
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Etudiant
                            </th>
							<th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Action
                            </th>
                        </tr>
                    </thead>
                    <tbody class="bg-white divide-y divide-gray-200">
                        {% for appointment in appointments %}
                            <tr>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                    {{ appointment.date }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                    {{ appointment.timeStart }}
                                </td>
								<td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                    {{ appointment.timeEnd }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                    {{ appointment.location }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                    {{ appointment.student.username }}
                                </td>
								<td class="px-6 py-4 whitespace-nowrap text-sm text-gray-90">
									<a href="{% url 'planning:edit_appointment' appointment.id %}" class="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
										Edit
									</a>
									<a href="{% url 'planning:delete_appointment' appointment.id %}" class="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
										Delete
									</a>
								</td>
                            </tr>
                        {% endfor %}
                    </tbody>
					<tfoot class="bg-gray-50">
						<tr>
							<td class="px-6 py-3 text-left">
								<a href="{% url 'planning:add_appointment' %}" class="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" style="background-color: #1f2937">
									Add New Appointment
								</a>
							</td>
						</tr>
					</tfoot>
                </table>
            {% else %}
                <p class="text-center text-gray-500">You have no appointments schffeduled.</p>
            <div class="text-center mt-4">
                <a href="{% url 'planning:add_appointment' %}" class="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" style="background-color: #1f2937">
                    Add New Appointment
                </a>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

planning/templates/appointment_secretary_list.html
{% extends 'base_generic.html' %}

{% block title %}My Appointments{% endblock %}

{% block content %}
<div>
	<h2 class="text-3xl font-extrabold text-gray-900">
		My Appointments instructor
	</h2>
</div>
<div class="flex items-center justify-center bg-gray-50" style="height: 80vh;display: flex;align-items: center;justify-content: center;">
    <div class="max-w-4xl w-full space-y-8">
        <div>
            {% if appointments %}
                <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                        <tr>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Date
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                TimeStart
                            </th>
							<th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                TimeEnd
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Location
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Etudiant
                            </th>
							<th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Instructor
                            </th>
							<th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Action
                            </th>
                        </tr>
                    </thead>
                    <tbody class="bg-white divide-y divide-gray-200">
                        {% for appointment in appointments %}
                            <tr>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                    {{ appointment.date }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                    {{ appointment.timeStart }}
                                </td>
								<td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                    {{ appointment.timeEnd }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                    {{ appointment.location }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                    {{ appointment.student.username }}
                                </td>
								<td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                    {{ appointment.instructor.username }}
                                </td>
								<td class="px-6 py-4 whitespace-nowrap text-sm text-gray-90">
									<a href="{% url 'planning:edit_appointment' appointment.id %}" class="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
										Edit
									</a>
									<a href="{% url 'planning:delete_appointment' appointment.id %}" class="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
										Delete
									</a>
								</td>
                            </tr>
                        {% endfor %}
                    </tbody>
					<tfoot class="bg-gray-50">
						<tr>
							<td class="px-6 py-3">
								<a href="{% url 'planning:add_appointment' %}" class="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" style="background-color: #1f2937; width: 187px;">
									Add New Appointment
								</a>
							</td>
						</tr>
					</tfoot>
                </table>
            {% else %}
                <p class="text-center text-gray-500">You have no appointments schffeduled.</p>
				<div class="text-center mt-4">
					<a href="{% url 'planning:add_appointment' %}" class="flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" style="background-color: #1f2937">
						Add New Appointment
					</a>
				</div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

planning/templates/appointment_student_list.html
{% extends 'base_generic.html' %}

{% block title %}My Appointments{% endblock %}

{% block content %}
<div>
    <h2 class=" text-3xl font-extrabold text-gray-900">
        My Appointments
    </h2>
</div>
<div class="flex items-center justify-center bg-gray-50" style="height: 80vh;display: flex;align-items: center;justify-content: center;">
    <div class="max-w-4xl w-full space-y-8">
        <div>
            {% if appointments %}
                <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                        <tr>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Date
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                TimeStart
                            </th>
							<th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                TimeEnd
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Location
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Instructor
                            </th>
                        </tr>
                    </thead>
                    <tbody class="bg-white divide-y divide-gray-200">
                        {% for appointment in appointments %}
                            <tr>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                    {{ appointment.date }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                    {{ appointment.timeStart }}
                                </td>
								<td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                    {{ appointment.timeEnd }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                    {{ appointment.location }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                    {{ appointment.instructor.username }}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                    <tfoot class="bg-gray-50">
						<tr>
							<td class="px-6 py-3 text-left">
								<a href="{% url 'planning:add_appointment' %}" class="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" style="background-color: #1f2937">
									Add New Appointment
								</a>
							</td>
						</tr>
					</tfoot>
                </table>
            {% else %}
                <p class="text-center text-gray-500">You have no appointments scheduled.</p>
                <div class="text-center mt-4">
                    <a href="{% url 'planning:add_appointment' %}" class="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" style="background-color: #1f2937">
                        Add New Appointment
                    </a>
                </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

planning/templates/edit_appointment.html
{% extends 'base_generic.html' %}

{% block title %}My Appointments{% endblock %}

{% block content %}
<div>
	<h2 class="text-3xl font-extrabold text-gray-900">
		Éditer un rendez-vous
	</h2>
</div>
<div class="flex items-center justify-center bg-gray-50" style="height: 80vh;display: flex;align-items: center;justify-content: center;">
    <div class="max-w-md w-full space-y-8">
		{% if messages %}
        <div class="alert alert-danger">
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        </div>
        {% endif %}
        <form method="post" class="space-y-6">
            {% csrf_token %}
            <div class="flex flex-col gap-5">
                <div>
                    <label for="student" class="sr-only">Étudiant</label>
                    <input id="student" name="student" type="text" readonly class="w-full px-3 py-2 placeholder-gray-500 text-gray-900 focus:outline-none sm:text-sm" value="{{ appointment.student.username }}">
                </div>
				{% if request.user.roles == "secretary" %}
				<div>
                    <label for="instructor" class="sr-only">Étudiant</label>
                    <input id="instructor" name="instructor" type="text" readonly class="w-full px-3 py-2 placeholder-gray-500 text-gray-900 focus:outline-none sm:text-sm" value="{{ appointment.instructor.username }}">
                </div>
				{% endif %}
                <div>
                    <label for="date" class="sr-only">Date</label>
                    <input id="date" name="date" type="date" required class="w-full px-3 py-2 placeholder-gray-500 text-gray-900 focus:outline-none sm:text-sm" value="{{ appointment.date|date:'Y-m-d' }}">
                </div>
                <div>
                    <label for="timeStart" class="sr-only">Heure de début</label>
                    <input id="timeStart" name="timeStart" type="time" step="3600" required class="w-full px-3 py-2 placeholder-gray-500 text-gray-900 focus:outline-none sm:text-sm" value="{{ appointment.timeStart|time:'H:i' }}">
                </div>
                <div>
                    <label for="timeEnd" class="sr-only">Heure de fin</label>
                    <input id="timeEnd" name="timeEnd" type="time" step="3600" required class="w-full px-3 py-2 placeholder-gray-500 text-gray-900 focus:outline-none sm:text-sm" value="{{ appointment.timeEnd|time:'H:i' }}">
                </div>
                <div>
                    <label for="location" class="sr-only">Lieu</label>
                    <input id="location" name="location" type="text" required class="w-full px-3 py-2 placeholder-gray-500 text-gray-900 focus:outline-none sm:text-sm" value="{{ appointment.location }}">
                </div>
            </div>
            <div>
                <button type="submit" class="w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-black focus:outline-none">
                    Enregistrer les modifications
                </button>
            </div>
        </form>
        <div class="text-center">
            <a href="{% url 'planning:appointment_list' %}" class="text-sm text-black-600 hover:text-gray-500">
                Retour à la liste des rendez-vous
            </a>
        </div>
    </div>
</div>

{% endblock %}