authapp/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import register, loginCustom, logoutCustom

app_name = 'auth'
urlpatterns = [
    path('login/', loginCustom, name='login'),
    path('logout/', logoutCustom, name='logout'),
    path('register/', register, name='register'),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
	path('', views.home, name='home'),
	path('account/', views.account, name='account'),
	path('settings/', views.settings, name='settings'),
	path('settings/delete/<int:user_id>/', views.delete_user, name='delete_user'),
	path('settings/update/<int:user_id>/', views.update_user, name='update_user'),
	path('student/', views.student_list, name='student_list'),
	path('student/<int:student_id>/', views.student_details, name='student_details'),
	path('instructor/', views.instructor_list, name='instructor_list'),
	path('instructor/<int:instructor_id>', views.instructor_details, name='instructor_details'),

	# path('', views.index, name='index'),
]

mon_projet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls')),
    path('planning/', include('planning.urls')),
]

planning/urls.py
from django.urls import path
from . import views

app_name = 'planning'
urlpatterns = [
    path('', views.appointment_list, name='appointment_list'),
	path('add/', views.add_appointment, name='add_appointment'),
	path('add/<int:user_id>/', views.add_appointment, name='add_appointment_with_id'),
	path('edit/<int:pk>/', views.edit_appointment, name='edit_appointment'),
	path('delete/<int:pk>/', views.delete_appointment, name='delete_appointment'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from authapp.models import CustomUser
from django.shortcuts import get_object_or_404
from authapp.forms import CustomUserEditForm
from planning.models import Appointment

# def index(request):
#     return HttpResponse("Hello, world. You're at the polls index.")

@login_required
def home(request):
    user = request.user
    if user.roles == 'student':
        return render(request, 'home_student.html', {'user': user})
    elif user.roles == 'instructor':
        return render(request, 'home_instructor.html', {'user': user})
    else:
        return render(request, 'home.html', {'user': user})

@login_required
def account(request):
    user = request.user
    return render(request, 'account.html', {'user': user})


@login_required
def settings(request):
    current_user = request.user
    if current_user.roles == 'secretary':
        users = CustomUser.objects.filter(roles__in=['student', 'instructor'])
    else:
        users = CustomUser.objects.filter(roles__in=['student', 'instructor', 'secretary'])
    return render(request, 'setting.html', {'users': users})

@login_required
def delete_user(request, user_id):
    if request.method == 'POST':
        user = get_object_or_404(CustomUser, id=user_id)
        user.delete()
        return redirect('main:settings')
    else:    
        return redirect('main:settings')

@login_required
def update_user(request, user_id):
    user = get_object_or_404(CustomUser, id=user_id)
    if request.method == 'POST':
        form = CustomUserEditForm(request.POST, instance=user)
        if form.is_valid():
            user = form.save(commit=False)
            password1 = request.POST.get('password1')
            password2 = request.POST.get('password2')
            if password1 and password1 == password2:
                user.set_password(password1)
            if 'hours_paid' in request.POST and request.POST.get('hours_paid').isdigit():
                user.hours_paid += int(request.POST.get('hours_paid'))
            user.save()
            return redirect('main:settings')
    else:
        form = CustomUserEditForm(instance=user)
    return render(request, 'update_user.html', {'form': form, 'user': user})



@login_required
def student_list(request):
    if request.user.roles == 'instructor':
        appointments = Appointment.objects.filter(instructor=request.user)
        students_with_appointments = set(appointment.student for appointment in appointments)
        students = CustomUser.objects.filter(roles='student', id__in=[student.id for student in students_with_appointments])
        return render(request, 'student_list.html', {'students': students})
    elif request.user.roles == 'secretary' or request.user.roles == 'admin':
        students = CustomUser.objects.filter(roles='student')
        return render(request, 'student_list.html', {'students': students})
    else:
        return redirect('main:home')

@login_required
def student_details(request, student_id):
    user = get_object_or_404(CustomUser, id=student_id)
    if user.roles == 'student':
        appointments = Appointment.objects.filter(student=user)
    else:
        appointments = Appointment.objects.filter(instructor=user)
    return render(request, 'student_details.html', {'student': user, 'appointments': appointments})

@login_required
def instructor_list(request):
    instructors = CustomUser.objects.filter(roles='instructor')
    return render(request, 'instructor_list.html', {'instructors': instructors})


@login_required
def instructor_details(request, instructor_id):
    user = get_object_or_404(CustomUser, id=instructor_id)
    appointments = Appointment.objects.filter(instructor=user)
    return render(request, 'instructor_details.html', {'instructor': user, 'appointments': appointments})

main/templates/account.html
{% extends 'base_generic.html' %}


{% block content %}
	<h2>Account</h2>
	<p>Hello, {{ user.username }}!</p>
	<p>{{user.roles}}</p>
{% endblock %}

main/templates/base_generic.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}My Site{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <!-- <nav class="bg-gray-800 p-4">
            <div class="container mx-auto flex justify-between items-center">
                <div>
                    <a href="{% url 'main:home' %}" class="text-white hover:text-gray-400">Home</a>
                </div>
                <div>
                    <a href="{% url 'main:account' %}" class="text-white hover:text-gray-400">Account</a>
                </div>
            </div>
        </nav> -->
    </header>
    <main class="bg-gray-50">
        <div class="flex">
            <div class="w-[calc(30%-50px)] bg-gray-800 p-4 flex flex-col justify-between text-white" style="height: 100vh;">
                <div class="flex flex-col gap-5">
                    <a href="{% url 'main:home' %}">Home</a>
                    <a href="{% url 'planning:appointment_list' %}">Planning</a>
                    {% if user.roles == 'instructor' or user.roles == 'secretary' or user.roles == 'admin' %}
                    <a href="{% url 'main:student_list' %}">Student List</a>
                    {% endif %}
                    {% if user.roles == 'secretary' or user.roles == 'admin' %}
                    <a href="{% url 'main:instructor_list' %}">Instructor List</a>
                    {% endif %}
                </div>
                <div class="flex flex-col gap-5">
                    <a href="{% url 'main:account' %}" class="block mt-2">Account</a>
                    {% if 'admin' in user.roles or 'secretary' in user.roles %}
                    <a href="{% url 'main:settings' %}" class="block mt-2">Setting</a>
                    {% endif %}
                    <form method="post" action="{% url 'auth:logout' %}">
                        {% csrf_token %}
                        <button type="submit" class="block w-full text-left">Logout</button>
                    </form>
                </div>
            </div>
            <div class="w-3/4 p-6"
            >
                {% block content %}{% endblock %}
            </div>
          </div>
    </main>
</body>
</html>

main/templates/base_generic_auth.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}My Site{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav>
            
        </nav>
    </header>
    <main>
        {% block content %}{% endblock %}
    </main>
</body>
</html>

main/templates/home.html
{% extends 'base_generic.html' %}

{% block title %}Home{% endblock %}

{% block content %}
  <h2 class="text-black-600">Home Page ADMIn</h2>
{% endblock %}

main/templates/home_instructor.html
{% extends 'base_generic.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="min-h-screen flex items-center justify-center bg-gray-50">
	<div class="max-w-md w-full space-y-8">
		<div>
			<h2 class="text-center text-3xl font-extrabold text-gray-900">
				Home Page instructor
			</h2>
		</div>
		<div>
			<p class="text-center text-3xl font-extrabold text-gray-900">
				Welcome, {{ user.username }}!
				{{ user.roles}}
				{{user.hours_paid}}
			</p>
		</div>
	</div>
</div>
{% endblock %}

main/templates/home_student.html
{% extends 'base_generic.html' %}

{% block title %}Student Dashboard{% endblock %}

{% block content %}
<h2 class="text-3xl font-extrabold text-gray-900">
	Student Dashboard
  </h2>
<div class="flex items-center bg-gray-50">
  <div class="max-w-md w-full space-y-8">
    <div>
      
    </div>
    <div class="space-y-6">
      <div>
        <h3 class="text-lg font-semibold">Hours Paid:</h3>
        <p>{{ user.hours_paid }}</p>
      </div>
      <div>
        <h3 class="text-lg font-semibold">Hours Taken:</h3>
        <p>{{ user.hours_taken }}</p>
      </div>
	  <div>
		<a href="{% url 'planning:appointment_list' %}">Planning</a>
	  </div>
    </div>
  </div>
</div>
{% endblock %}

main/templates/instructor_details.html
{% extends 'base_generic.html' %}

{% block title %}Student Details{% endblock %}

{% block content %}
<h1>instructor Details</h1>
<p>{{ instructor.username }}</p>
{% if request.user.roles == 'secretary' or request.user.roles == 'admin' %}

<div class="flex items-center justify-center bg-gray-50" style="height: 80vh;display: flex;align-items: center;justify-content: center;">
    <div class="max-w-4xl w-full space-y-8">
        <div>
            {% if appointments %}
                <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                        <tr>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Date
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                TimeStart
                            </th>
							<th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                TimeEnd
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Location
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Etudiant
                            </th>
							<th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
								Instructor
							</th>
                        </tr>
                    </thead>
                    <tbody class="bg-white divide-y divide-gray-200">
                        {% for appointment in appointments %}
                            <tr>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                    {{ appointment.date }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                    {{ appointment.timeStart }}
                                </td>
								<td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                    {{ appointment.timeEnd }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                    {{ appointment.location }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                    {{ appointment.student.username }}
                                </td>
								<td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                    {{ appointment.instructor.username }}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p class="text-center text-gray-500">You have no appointments schffeduled.</p>
            {% endif %}
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

main/templates/instructor_list.html
{% extends 'base_generic.html' %}

{% block title %}Home{% endblock %}

{% block content %}

<h1>instructor liste</h1>

{% for instructor in instructors %}
    <a href="{% url 'main:instructor_details' instructor.id %}">{{ instructor.username }}</a>
{% endfor %}

{% endblock %}

main/templates/setting.html
{% extends 'base_generic.html' %}

{% block title %}Setting{% endblock %}

{% block content %}
<h2 class="text-black-600 text-4xl mb-20">Setting Page</h2>
<div class="flex">
  <div class="w-full">
    <table class="divide-y divide-gray-200">
      <thead class="bg-gray-50">
        <tr>
          <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
            Username
          </th>
		  <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
			Role
		  </th>
		  <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
			hour_paid
		  </th>
        </tr>
      </thead>
      <tbody class="bg-white divide-y divide-gray-200">
        {% for user in users %}
          {% if user != request.user %}
            <tr>
              <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                {{ user.username }}
              </td>
			  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
				{{ user.roles }}
			  </td>
			  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
				{{ user.hours_paid }}
			  </td>
              <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                <div class="flex gap-4">
                  <a href="{% url 'main:update_user' user.id %}" class="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-gray-600 hover:bg-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-grey-500">
                    Edit
                  </a>
                  <form action="{% url 'main:delete_user' user.id %}" method="post">
                    {% csrf_token %}
                    <div class="flex gap-4">
                      <button type="submit" class="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-red-600 hover:bg-red-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500">
                        Delete
                      </button>
                    </div>
                  </form>
                </div>
              </td>
            </tr>
          {% endif %}
        {% endfor %}
      </tbody>
      <tfoot class="bg-gray-50">
        <tr>
          <td  class="px-6 py-3 text-right">
            <a href="{% url 'auth:register' %}" class="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white  hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" style="background-color: #1f2537;">
              Add User
            </a>
          </td>
        </tr>
      </tfoot>
    </table>
  </div>
</div>
{% endblock %}

main/templates/student_details.html
{% extends 'base_generic.html' %}

{% block title %}Student Details{% endblock %}

{% block content %}
<h1>Student Details</h1>
<p>{{ student.username }}</p>
<p> heures payées : {{student.hours_paid}}</p>
<p> heures prises : {{student.hours_taken}}</p>
{% if request.user.roles == 'secretary' or request.user.roles == 'admin' %}

<div class="flex items-center justify-center bg-gray-50" style="height: 80vh;display: flex;align-items: center;justify-content: center;">
    <div class="max-w-4xl w-full space-y-8">
        <div>
            {% if appointments %}
                <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                        <tr>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Date
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                TimeStart
                            </th>
							<th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                TimeEnd
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Location
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Etudiant
                            </th>
							<th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
								Instructor
							</th>
                        </tr>
                    </thead>
                    <tbody class="bg-white divide-y divide-gray-200">
                        {% for appointment in appointments %}
                            <tr>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                    {{ appointment.date }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                    {{ appointment.timeStart }}
                                </td>
								<td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                    {{ appointment.timeEnd }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                    {{ appointment.location }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                    {{ appointment.student.username }}
                                </td>
								<td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                    {{ appointment.instructor.username }}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p class="text-center text-gray-500">You have no appointments schffeduled.</p>
            {% endif %}
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

main/templates/student_list.html
{% extends 'base_generic.html' %}

{% block title %}Home{% endblock %}

{% block content %}

<h1>student liste</h1>

{% for student in students %}
    <a href="{% url 'main:student_details' student.id %}">{{ student.username }}</a>
{% endfor %}

{% endblock %}

main/templates/update_user.html
{% extends 'base_generic.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="flex items-center justify-center bg-gray-50">
	<div class="max-w-md w-full space-y-8">
		<div>
			<h2 class="text-center text-3xl font-extrabold text-gray-900">
				Update User
			</h2>
		</div>
		<form method="post" class="space-y-6">
			{% csrf_token %}
			<div class="flex flex-col gap-5">
				<div>
					<label for="username" class="sr-only">Username</label>
					<input id="username" name="username" type="text" required class="w-full px-3 py-2 placeholder-gray-500 text-gray-900  focus:outline-none sm:text-sm" placeholder="Username" value="{{ user.username }}">
				</div>
				<div>
					<label for="password1" class="sr-only">Password1</label>
					<input id="password1" name="password1" type="password"  class="w-full px-3 py-2 placeholder-gray-500 text-gray-900  focus:outline-none  sm:text-sm" placeholder="Password">
					{% if form.password1.errors %}
						<p class="text-red-500 text-sm mt-1">{{ form.password1.errors }}</p>
					{% endif %}
				</div>
				<div>
					<label for="password2" class="sr-only">Password confirmation</label>
					<input id="password2" name="password2" type="password"  class="w-full px-3 py-2 placeholder-gray-500 text-gray-900 focus:outline-none sm:text-sm" placeholder="Confirm Password">
					{% if form.password2.errors %}
						<p class="text-red-500 text-sm mt-1">{{ form.password2.errors }}</p>
					{% endif %}
				</div>
				<div>
					<fieldset>
						<legend>Roles:</legend>
						<div class="flex gap-3">
							<div>
								<input id="student" name="roles" type="radio" value="student" class="mr-2" {% if user.roles == 'student' %}checked{% endif %}>
								<label for="student">Student</label>
							</div>
							<div>
								<input id="instructor" name="roles" type="radio" value="instructor" class="mr-2" {% if user.roles == 'instructor' %}checked{% endif %}>
								<label for="instructor">Instructor</label>
							</div>
							{% if request.user.roles == 'admin' %}
							<div>
								<input id="secretary" name="roles" type="radio" value="secretary" class="mr-2" {% if user.roles == 'secretary' %}checked{% endif %}>
								<label for="secretary">Secretary</label>
							</div>
							<div>
								<input id="admin" name="roles" type="radio" value="admin" class="mr-2" {% if user.roles == 'admin' %}checked{% endif %}>
								<label for="admin">Admin</label>
							</div>
							{%	endif %}
						</div>
						{% if form.roles.errors %}
							<p class="text-red-500 text-sm mt-1">{{ form.roles.errors }}</p>
						{% endif %}
					</fieldset>
				</div>
				{% if user.roles == 'student' %}
				<div>
					<label for="hours_paid" class="sr-only">Hours Paid</label>
					<input id="hours_paid" name="hours_paid" type="number" class="w-full px-3 py-2 placeholder-gray-500 text-gray-900  focus:outline-none  sm:text-sm" placeholder="Hours Paid">
					{% if form.hours_paid.errors %}
						<p class="text-red-500 text-sm mt-1">{{ form.hours_paid.errors }}</p>
					{% endif %}
				</div>
				{% endif %}
			</div>
			<div>
				<button type="submit" class="w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-black focus:outline-none">
					Update
				</button>
			</div>
		</form>
		<div class="text-center">
			<a href="{% url 'main:settings' %}" class="text-sm text-black-600 hover:text-gray-500">
			  Back to Settings
			</a>
		  </div>
	</div>
</div>
{% endblock %}